-- begin RADIUS_STUDENT
alter table RADIUS_STUDENT add constraint FK_RADIUS_STUDENT_ON_GROUP foreign key (GROUP_ID) references RADIUS_GROUP(ID)^
create index IDX_RADIUS_STUDENT_ON_GROUP on RADIUS_STUDENT (GROUP_ID)^
create index IDX_RADIUS_STUDENT__LAST_NAME on RADIUS_STUDENT (LAST_NAME)^
-- end RADIUS_STUDENT
-- begin RADIUS_GROUP
create unique index IDX_RADIUS_GROUP_UNIQ_NUMBER_ on RADIUS_GROUP (NUMBER_)^
create unique index IDX_RADIUS_GROUP_UNIQ_FACULTY on RADIUS_GROUP (FACULTY)^
create index IDX_RADIUS_GROUP_NUMBER_ on RADIUS_GROUP (NUMBER_)^
-- end RADIUS_GROUP
